### ISSUE TITLE
№ 10 - PostgreSQL

### ISSUE THREAD

**Issue by kairat-symanov** [CRM-system/crm#10]
Конечный результат:
- изучить PostgreSQL, для хранения данных в этой базе;
- каждому установить PostgreSQL на свой компьютер.
План решения:
- найти официальную документацию и изучить материал;
- в составе команды обсудить и понять принцип работы и особенности PostgreSQL;
Мотивация:
Необходима в дальнейшей работе, т.к. эта база самая распространённая. 
Обсуждение и установка 12.01.2019.

**Comment by kairat-symanov** [comment]
Установил на компьютер PostgreSQL

**Comment by aibek-abenov** [comment]
Установил на компьютер PostgreSQL

**Comment by primbayev** [comment]
Установил на компьютер PostgreSQL

**Comment by Danny-Marco** [comment]
Установил Postgresql на свой компьютер.Рассмотрел примеры по работе с данной СУБД. Обсудил с коммандой

**Comment by aibek-abenov** [comment]
Установил на компьютер PostgreSQL
