### ISSUE TITLE
№ 11 - SemanticUI

### ISSUE THREAD

**Issue by kairat-symanov** [CRM-system/crm#11]
Конечный результат:
Изучить SemanticUI, как альтернативу Bootstrap.
План решения:
Найти официальную документацию и самостоятельно изучить.
Мотивация:
Для саморазвития и улучшения своих  знаний.
До 14.01.2019.

**Comment by Danny-Marco** [comment]
общее представление понял(примерно тоже ,что и bootstrap), а уже что-то более конкретное будем смотреть в документации.

**Comment by primbayev** [comment]
общее представление понял, посмотрев видеоуроки

**Comment by kairat-symanov** [comment]
Изучил SemanticUI на сайте https://semantic-ui.com/, также изучил настройки на https://github.com/doabit/semantic-ui-sass

**Comment by aibek-abenov** [comment]
общее представление понял, посмотрев видеоуроки
