### ISSUE TITLE
№12 - Создание админки проекта

### ISSUE THREAD

**Issue by kairat-symanov** [CRM-system/crm#12]
Конечный результат:
Создать админку, для входа админу для просмотра, создания, редактирования, удаления сотрудников и товаров.
План решения:
Создать в app/controller папку admin в ней создать:
- контроллер и вьюхи "worker" - CRUD;
- модель"function" с полями name, functinable_id, funtinable_type, access, role_id, а также контроллер - CRUD кроме "show";

Мотивация:
Необходимо предоставить заказчику результат работы за итерацию №1.
Критерии приёмки:
>Если я залогинен как админ
>И захожу на localhost:3000/admin
>То могу увидеть кнопки "worker"

>Если я нажму на кнопку "worker"
>То могу увидеть на пустой странице кнопку "Create worker"

>Если я нажму на кнопку "Create worker"
>То могу увидеть форму с полями "nickname", "email", "password"
>После того как заполню поля, я нажму на кнопку "Create"
>То меня перекинет на страницу "worker", с созданным сотрудником и кнопками "Edit", "Delete", а также кнопкой "Create worker" ниже

>Если я нажму на кнопку "Edit"
>То могу увидеть Devise форму для редактирования
>После того как заполню поля, я нажму на кнопку "Update"
>То меня перекинет на страницу "worker", со списком  сотрудников и кнопками "Edit", "Delete", а также кнопкой "Create worker" ниже

>Если я нажму на кнопку "Delete"
>То могу увидеть всплывающее окно с записью предупреждением "Вы действительно хотите удалить сотрудника" и кнопками "Да" и "Нет"
>Если я нажму на кнопку "Да" 
>То сотрудник удалится
>Если я нажму на кнопку "Нет"
>То всплывающее окно с записью предупреждением "Вы действительно хотите удалить сотрудника" и кнопками "Да" и "Нет", исчезнет

Критерии приёмки для "product" такие же как и для "worker"

**Comment by aibek-abenov** [comment]
1.Реализовал админскую часть,
2.написал контроллер  и вьюхи для админа(сущность Worker) со всей CRUD операцией,
3.написал навбар для админа.
 Потребовалось 6 часов работы№
