### ISSUE TITLE
№13 - Создание сущности "Products"

### ISSUE THREAD

**Issue by kairat-symanov** [CRM-system/crm#13]
Конечный результат:
Создание контроллера и вьюх "Products" для пользовательской части 
План решения:
- создать контроллер "Products" с экшинами "index", "show";
- создать вьюхи "index", "show", для просмотра всех товаров и по отдельности.
Мотивация:
На данный момент клиент ничего не видит
Критерии приёмки:
>Если я залогинен как сотрудник
>То могу увидеть кнопку "Product"

>Если я нажму на кнопку "Product"
>То могу увидеть список товаров с "title", "description", "price"
>При этом "title" должен быть ссылкой

>Если я нажму на "title" продукта
>То могу увидеть один продукт с "title", "description", "price" и кнопкой "Back" ниже
>Если я нажму на кнопку "Back"
>То меня перекинет на страницу "Product"

**Comment by Danny-Marco** [comment]
1.Создал модель Product с полями name,description,price.
2.Создал Контроллер Products и 2 экшена: index и show.
3.Создал вьюхи Index и show

**Comment by Danny-Marco** [comment]
4.Сделал рутовой страницу products#index
5.Добавил в навбар ссылку Проодукты

**Comment by Danny-Marco** [comment]
6.Реализовал весь CRUD для будущей админки.

**Comment by Danny-Marco** [comment]
7.Добавил в админку Product.

**Comment by Danny-Marco** [comment]
В общей сложности потратил на работу 6 часов планировал всё сделать за 3. Задержка получилась из-за проблем с git
