### ISSUE TITLE
# 15 Изучить основные комманды git. Merge, работа с ветками. 

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#16]
Сделать себе список комманд для git.
Должны уметь:
-делать слияние со своей ветки на ветку мастер
-разрешать конфликты
-переключаться между ветками
Желательно потренироваться на "тестовом" проекте.

**Comment by Danny-Marco** [comment]
На изучение материала было потрачено 2 часа.На данный момент разобрался с командами обязательными к изучению в тикете. Пока решать задачи с gitом на данном этапе более - менее получается.

**Comment by primbayev** [comment]
Разобрался с командами в процессе работы над своим тикетом. Пока решать задачи с gitом на данном этапе более - менее получается.

**Comment by aibek-abenov** [comment]
Ознакомился с материалами в интернете,разобрался с командами в процессе работы над своим тикетом. Пока решать задачи с gitом на данном этапе более - менее получается.

**Comment by kairat-symanov** [comment]
В составе команды отработали данный тикет, методом проб и ошибок изучили порядок работы в Git репозитории. Изучили и отработали на практике основные команды. Написал шпаргалку и скинул в общий чат.
