### ISSUE TITLE
№ 16 Реализовать работу с изображениями для модели Product.

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#17]
Задача пока ни для кого не назначена.Как у одного из участников команды появится свободное время можно будет приступать к решению задачи

**Comment by aibek-abenov** [comment]
Реализовал отображение изображении для товаров,
выявил баг с навбаром,решил ее. 
Потребовалось 1.5 часа.

**Comment by aibek-abenov** [comment]
Планировал затратить 2 часа.
