### ISSUE TITLE
№ 17 Реализовать функции Просмотр списка товаров,просмотр настроек товаров,изменение настроек товаров

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#18]
Конечный результат.
1. Сотрудник заходит в "Должности" и должен увидеть функцию Просмотра списка товаров
2.Сотрудник заходит заходит в "Должности" и должен увидеть функцию Просмотра какого-то товара
3.Сотрудник имеет возможность редактирования товара(цена,описание,название)
Критерий приёмки:
1.
>Юзер под созданным сотрудником видит в навбаре ссылку "товары">
<Заходит в "Товары" и видит список всех товаров>
2.
<Юзер под сотрудником заходит в опиание товара, но не может что то изменить,только созерцать>
3.
<Юзер под сотрудником заходит в опиание товара, может отредактировать товар(цена,описание,название)>

**Comment by Danny-Marco** [comment]
Планируемое время на решение задачи 3 часа

**Comment by primbayev** [comment]
Выполнил задание за 1 час
