### ISSUE TITLE
№ 19. Обсудить всей командой и наставником реализацию функций.

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#20]
Задача: Всем участникам комманды понять реализацию логики функций. Обдумать и обсудить с наставником оптимальные решения данной задачи.Возможно предложить свой метод.Главная задача это ПОНЯТЬ.

Примерное время на обсуждение тикета 1 - 3 часа.

**Comment by Danny-Marco** [comment]
Обсудили всей командой решение задачи.Потратили 1 час

**Comment by aibek-abenov** [comment]
Обсудили с командой.
Задачу понял.

**Comment by kairat-symanov** [comment]
Обсуждение тикета прошло в составе команды в присутствии наставника. Потрачено 1 час времени.

**Comment by primbayev** [comment]
Обсудили всей командой решение задачи.Потратили 1 час

**Comment by Danny-Marco** [comment]
Общее затраченное время 1 час
