### ISSUE TITLE
№ 20 Реализовать дизайн проекта.Всех вьюх админской и клиентской части

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#21]
Для решения задачи использовать  SemanticUI.
Критерии приёмки:
На данном этапе  у проекта должен быть красивый дизайн и интуитивно понятная логика.

**Comment by Danny-Marco** [comment]
Ориентировачное время решения задачи 3 часа.

**Comment by kittiehawk** [comment]
Планируемое время решения задачи 3 часа

**Comment by Danny-Marco** [comment]
Подключил semantic ui локально на проекте.Реализовал дизайн отображения списков товаров,сотрудников.Не удалось реализовать остальной функционал.На данном этапе потратил на решение задачи 3 часа

**Comment by Danny-Marco** [comment]
Реалтзовал дизай проекта с semantic ui.
Общее время решения здачи 4 часа
