### ISSUE TITLE
№ 22 Создать сиды сотрудников.

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#23]
Должны быть:
-опрератор(просмотр спика товаров)
- Директор (полный доступ, кроме удаления товаров.)
Мотивация
-Во вторник должны представить проект заказчику в котором реализован функционал создания должности и предоставление должности возможностей

**Comment by primbayev** [comment]
Планирую сделать 20 минут

**Comment by primbayev** [comment]
Сделал за 25 минут
