### ISSUE TITLE
№ 23 Установить и настроить проект с semantic ui.

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#24]
Все участники команды должны установить нужные гемы и настроить проект с semantic ui.
-у всех участников команды дизайн проекта должен отображаться одинаково
-не должно выскакивать ошибок и проект не должен "падать"

**Comment by Danny-Marco** [comment]
Установил semantic ui. Всё работает, ничего не падает.

**Comment by aibek-abenov** [comment]
Установил semantic ui. Всё работает.

**Comment by primbayev** [comment]
Установил semantic ui. Всё работает, ничего не падает.

**Comment by kairat-symanov** [comment]
Семантик установил, приложение работает.
