### ISSUE TITLE
№ 24 Реализовать прокрутку

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#25]
- подключить gem paginate (или любой другой)
- реализовать в проекте прокрутку
Критерий приёмки
- на странице вывода всех товаров(если товаров больше 10),внизу должно выводиться построчное отображение страниц.
- протестировать можно на выводе 3 товаров на странице.

**Comment by primbayev** [comment]
Планирую сделать за 15 минут

**Comment by primbayev** [comment]
сделал за 15 минут
