### ISSUE TITLE
№ 25 Протестировать готовую часть проекта

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#27]

**Comment by Danny-Marco** [comment]
-протестировать возможности сотрудников
1.оператор
    -создать учётную запись сотрудника оператор 
   - предоставить ему полномочия по просмотру товара
    -убедиться ,что он имеет только те права которые ему предоставили(просмотр товаров).Не должен видеть кнопки редактировать товары,удалять товары.
    -оператор в навбаре не должен видеть ссылки "должности","сотрудники".Должен видеть только ссылку "товары". 
2.директор
    -создать учётную запись сотрудника директор
   - предоставить ему полномочия(может и видит всё кроме удаления товаров,дублирования должности)
    - убедиться ,что он имеет только те права которые ему предоставили(не должен иметь возможность удалять товары)
    -директор в навбаре должен видеть ссылки "товары","должности","сотрудники"
   - директор не должен видеть кнопку "удалить товар"
    -директор не должен видеть кнопку создать копию должности.

**Comment by primbayev** [comment]
Проверил все ситуации. Работает все корректно

**Comment by aibek-abenov** [comment]
Протестировал.Визуально все работает правильно.

**Comment by Danny-Marco** [comment]
Протестировал.Визуально все работает правильно.

**Comment by kairat-symanov** [comment]
Протестил готовую часть, выдала ошибку при редактировании роли. Исправили баг, всё работает корректно.
