### ISSUE TITLE
№ 26 Обсуждение с командой реализации сущности Заказы. 

### ISSUE THREAD

**Issue by aibek-abenov** [CRM-system/crm#28]
### Зачем это нужно
Обсудить с командой детали  реализации сущности Заказы,его поля и связи.

### Планируемое время
3 часа

**Comment by Danny-Marco** [comment]
Обсудили.Пришли к консенсусу.

**Comment by kairat-symanov** [comment]
Долго обсуждали, выяснили требования заказчика, вроде разобрались что делать)

**Comment by primbayev** [comment]
Долго обсуждали, выяснили требования заказчика.Пришли к консенсусу.

**Comment by aibek-abenov** [comment]
Обсуждали долго.Пришли к единному мнениюю
