### ISSUE TITLE
№ 27 Обсуждение с командой реализацию статуса заказа.

### ISSUE THREAD

**Issue by aibek-abenov** [CRM-system/crm#29]
### Зачем это нужно
Обсудить использование enuma.
Выявить все за и против.

### Планируемое время 
 1 час

**Comment by Danny-Marco** [comment]
Обсудили с командой реализацию статуса.

**Comment by kairat-symanov** [comment]
Обсудили и изучили командой преимущества "enum", решили его использовать.

**Comment by primbayev** [comment]
Обсудили с командой реализацию статуса.

**Comment by aibek-abenov** [comment]
Обсудили с командой реализацию статуса.
