### ISSUE TITLE
№ 28 Реализация сущности Order.

### ISSUE THREAD

**Issue by aibek-abenov** [CRM-system/crm#30]
### Конечный результат
В админской части CRM должна появиться модель Order, связать его с сущностью Product .
У него  будут поля : product_id:integer, product_name:string, product_price:decimal, product:quantity:decimal,  client_name:string, client_phone:string, client_email:string, delivery_type:string, order_price:decimal, status:integer.

### Зачем это нужно
Чтобы  в последующем хранить и обрабатывать данные о заказах.

### Критерии приемки
В проекте в папке db/schema должна появиться схема orders c полями:
product_id:integer, product_name:string, product_price:decimal, product:quantity:decimal,  client_name:string, client_phone:string, client_email:string, delivery_type:string, order_price:decimal, status:integer.В модели Order должны написать валидации .

### Планируемое время работы
 5 часов

**Comment by kairat-symanov** [comment]
Взял этот тикет на реализацию, предполагаемое время 5 часов.

**Comment by kairat-symanov** [comment]
Завершил данный тикет. За 2 часа времени.

**Comment by kairat-symanov** [comment]
Не работала кнопка "Удалить", устранил неисправность. 
Потрачено времени 10 мин.
