### ISSUE TITLE
№ 29 Сделать Landing Page и реализовать оформление заказа

### ISSUE THREAD

**Issue by aibek-abenov** [CRM-system/crm#31]
**Конечный результат**
В клиентской части CRM должна появиться рутовая страница, которая будет отображаться список товаров, по клику на один товар будем переходить во вьюху products/show, где описание этого товара и форма. 

**Зачем это нужно**
Это будет Landing Page.
Эту нужно для тестирования CRM - системы. Для работы с заказами.

**Критерии приемки**
Кликая на  сссылку(название товара),переходим на products/show
где описание этого товара и форма.
Форма для клиента с клиента с тремя полями , Его номером телефона,Его  имени, Его emailом.
В форме создаётся новый заказ.Все данные (кроме номера телефона, имени и emailа клиента) отправляются в hidden tag.Добиться создания нового заказа через форму,
после отправки данных из формы проверить через консоль был ли создан заказ.

**Планируемое время работы**

**Comment by aibek-abenov** [comment]
Переделать индекс продукта ,
сделать из него Landing Page,для тестирования.
Когда проходишь по ссылке localhost3000
видишь страницу магазина с одним товаром.
И форма для клиента с одним полем , Его номером телефона.

**Comment by aibek-abenov** [comment]
переделать вьюху index product

**Comment by primbayev** [comment]
предполагаемое время 3 часов.

**Comment by primbayev** [comment]
Сделал задание за 8 часов
