### ISSUE TITLE
№ 30 Написать функцию для редактирования заказов.

### ISSUE THREAD

**Issue by aibek-abenov** [CRM-system/crm#32]
**Конечный результа**т
Когда мы заходим в Систему как Оператор , мы можем редактировать заказы

**Зачем это нужно**
Когда мы будем заходим в Систему как Оператор,у нас должно быть право на редактирование заказа . Потому что важно изменить статус заказа после его обработки.Данное решение было обсуждено с заказчиком на встрече 22.01.2019

**Критерии приемки**
Когда будем кликать на "Новые " на вьюхе индекс будет только список заказов со статусом :new_order, и напротив каждого заказа будет кнопка "Обработать".По клику на него нас будет перекидывать во вьюху :edit  с формой для редактирования.

**Планируемое время работы**
4 часа

**Comment by kairat-symanov** [comment]
Данный тикет выполнен 22.01.2019, **потратил 3 часа времени**, но для уточнения деталей не был завершён в этот день.
28.01.2019 тикет доработан, реализовано ограничение функций сотрудникам по редактированию и удалению "Заказов", **потратил 30 мин. времени**.
