### ISSUE TITLE
№ 31 Ссылка "Заказы" в Навбаре для оператора.

### ISSUE THREAD

**Issue by aibek-abenov** [CRM-system/crm#33]
Конечный результат
В навбаре будет поле "Заказы".

Зачем это нужно
Для удобства пользования CRM - системой для всех пользователей,точнее сотрудников. Данное решение было обсуждено с заказчиком на встрече 22.01.2019

Критерии приемки
Когда сотрудник будет заходить в Систему в Навбаре будет поле Заказы.
Сделать его ссылкой по клику на  него будем переходить во вьюху со следующими статусами заказов:
Новые
Обработанные
Отказанные

Планируемое время работы
1 час

**Comment by kairat-symanov** [comment]
Добавил ссылку "Заказы" в навбар.

**Comment by kairat-symanov** [comment]
Потратил 30 мин.

**Comment by Danny-Marco** [comment]
Отказались от  реализации вывода количества новых заказов в навбаре ,ссылке "заказы"
