### ISSUE TITLE
№32 Обработка заказа Оператором .

### ISSUE THREAD

**Issue by aibek-abenov** [CRM-system/crm#34]
### Конечный результат

- Во вьюхе индекс для оператора  будут от ображаться список статусов.
Когда оператор кликнет на статус "Новые", он будет переходить на список заказов со статусом :new . 
Когда оператор кликнет на статус "Новые", он будет переходить на список заказов со статусом :new . 
- Напротив каждого заказа будет  кнопка "Обработать" .
По клику на кнопку "Обработать"   мы будем переходить на форму т.е. экшен :update,для того чтобы изменить данные о заказе,имеется ввиду дописать данные о клиенте.
- Его адрес, тип доставки, цена заказа, количество заказанного товара ,изменение статуса на :processed. Помимо кнопки "Подтвердить", имеется ввиду изменения, будет кнопка  "Отменить".
- По клику на кнопку "Отменить" изменить только статус заказа на :refused.

### Зачем это нужно

Оператор будет являться тем сотрудником,который будет обрабатывать заказы,имеется ввиду дописать данные о клиенте.
- Его адрес, тип доставки, цена заказа, количество заказанного товара ,изменение статуса на :processed.

### Критерии приемки
В базе данных CRM - системы будут сохранены измененные(редактированные ) оператором данные. Можно будет вывести эти данные либо на консоли ,либо в браузере.

### Планируемое время работы
3 часа

**Comment by Danny-Marco** [comment]
Реализовал тикет. Общее затраченное время 5 часов.Планировал 3 часа
