### ISSUE TITLE
№ 33 Реализовать ограничения удаления заказов для оператора

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#35]
Конечный результат
Оператор будет проходить в админскую  часть CRM , и будет видеть во вьюхе products/index  заказы со статусом :new_order и редактировать  их ,но не удалять.

Зачем это нужно
В данной CRM - системе доступ на удаление будут иметь суперадмин и директор .У оператора не будет возможности удалять заказы. Данное решение было обсуждено с заказчиком на встрече 22.01.2019

Критерии приемки
Когда мы зайдем в Систему под Оператором и когда будем кликать на "Новые " на вьюхе индекс будет только список заказов со статусом :new_order и напротив каждого заказа будет только кнопка "Обработать".Если мы будем заходить в Систему под Суперадмином помимо кнопки "Обработать" напротив заказа ,также будет кнопка "Удалить". 

Планируемое время работы
3 часа.

**Comment by kairat-symanov** [comment]
Добавил ссылку 'Заказы' в навбар. Прописал в модели и контроллере 'Заказы' методы предоставляющие права сотрудникам. Потратил 1 час.

**Comment by kairat-symanov** [comment]
Прописал в модель "Сотрудники" и контроллер "Заказы" методы предоставляющие права сотрудникам(edit, create, destroy, new). Предыдущий комментарий ошибочный. Потратил 1 час.

**Comment by kairat-symanov** [comment]
Выполнил **3-й пункт** данного тикета **"Оператор не должен видеть кнопки удаления заказов"**, также реализовал функцию **"если нет прав на редактирование"**, то кнопка редактировать не видна.
Потратил **1 час** времени.

**Comment by kairat-symanov** [comment]
Общее время выполнения 2 часа.
