### ISSUE TITLE
 № 34 Реализовать логику для вывода заказов по статусам new_order, refused, proccessed во вьюхе order/index.

### ISSUE THREAD

**Issue by aibek-abenov** [CRM-system/crm#36]
## Конечный результат
В админской части CRM должна появиться рутовая страница, которая будет открываться сразу после того, как пользователь совершит вход в систему.

## Зачем это нужно
Рутовая страница админки должна содержать заказы клиентов, это один из самых важных функционалов системы и поэтому эта информация должна отображаться именно на этой странице. Данное решение было обсуждено с заказчиком на встрече 22.01.2019

## Критерии приемки 
1. Должна быть реализована вьюха со следующими статусами заказов: 
     - Новые
     - Обработанные
     - Отказанные
2. Сделать их ссылками.По клику на них переходить на вьюху orders/index.
     - Когда будем кликать на "Новые " на вьюхе индекс будет только список заказов со статусом :new_order. 
     - Когда будем кликать на "Обработанные " на вьюхе индекс будет только список заказов со статусом :processed. 
     - Когда будем кликать на "Отказанные " на вьюхе индекс будет только список заказов со статусом :refused. 

## Планируемое время работы
5 часов (выставляется разработчиком или аналитиком после согласования с разработчиком)

**Comment by primbayev** [comment]
Реализовал логику вывода заказов по статусу

**Comment by Danny-Marco** [comment]
Создал вьюху "status" в контроллере orders в которой будут выводиться ссылки на вывод заказов с определённым статусом.Пытался реализовать логику вывода заказов с разными статусами.Потратил 4 часа.
