### ISSUE TITLE
#37 Вывести на главную страницу "Заказы" все статусы.

### ISSUE THREAD

**Issue by kairat-symanov** [CRM-system/crm#37]
**Конечный результат:**
В админской части CRM во вкладке "Заказы" должны появиться ссылки на все статусы, которые будут отображаться сразу после того, как пользователь перейдёт во вкладку "Заказы".
**Зачем это нужно:**
Вкладка "Заказы" должна содержать ссылки на статусы, нажав на каждый из них пользователь перейдёт на это статус и увидит внизу таблицу со списком заказов согласно выбранного статуса.
**Критерии приёмки:**
1. Во вьюхе index прописать все предполагаемые статусы:

- для операторов;

- для складских работников;

- напоминание;

- проблемные;

- прочие.
2. Сделать их ссылками, нажав на каждый из них пользователь перейдёт на это статус и увидит внизу таблицу со списком заказов согласно выбранного статуса.

Время выполнения: 1 час

**Comment by kairat-symanov** [comment]
Тикет отработан, потрачено времени - 1 час.

**Comment by aibek-abenov** [comment]
После обсуждения с заказчиком отпало надобность в следующих статусах: call-center, проблемные, отсутствие продукта и архив.

**Comment by kairat-symanov** [comment]
Исправил дополнение, потратил время 5 мин.

**Comment by kairat-symanov** [comment]
Доработал вьюху, вывел все статусы со счётчиками в ряд. Потратил 2 часа.
