### ISSUE TITLE
№ 39 Сделать счетчик для всех статусов

### ISSUE THREAD

**Issue by primbayev** [CRM-system/crm#39]
## Конечный результат
На странице заказов, напротив каждого статуса, должна быть цифра определяющая кол-во заказов данным статусом.

## Зачем это нужно
Для удобства мониторинга заказов.

## Критерии приемки 
После нажатия на любой статус, страница заказов должна вывести заказы, кол-во которых должна совпадать с цифрой, которая находится напротив данного статуса. 

## Планируемое время работы
5 часов

**Comment by kairat-symanov** [comment]
Тикет исполнен для статусов оператора. 
Время выполнения - 1,5 часа
