### ISSUE TITLE
№ 42 Создать модель order_status

### ISSUE THREAD

**Issue by primbayev** [CRM-system/crm#42]
## Конечный результат
Нужно создать модель с полями: title, description. Эта модель будет иметь связь с моделью Role.

## Зачем это нужно
Пользователи меняют статусы заказов. Нужно установить с какими именно статусами имеет право работать пользователь.

## Критерии приемки 
В модели order_status должны быть валидации на поля title и description. 

## Планируемое время работы
1 час

**Comment by kairat-symanov** [comment]
Тикет исполнен, потраченное время - 1 час.
