### ISSUE TITLE
№ 44 Установить связь многие ко многим между моделями Role и Order_status

### ISSUE THREAD

**Issue by primbayev** [CRM-system/crm#44]
## Конечный результат
Нужно создать промежуточную модель Role_order_status.

## Зачем это нужно
Пользователи меняют статусы заказов. Нужно установить с какими именно статусами имеет право работать пользователь. Для этого нужна связь многие ко многим между моделями Role и Order_status.

## Критерии приемки 
Нужно зайти в консоль. В консоли создать запись модели Role_order_status. Запись должна создаться без ошибок.

## Планируемое время работы
1 час

**Comment by kairat-symanov** [comment]
Тикет исполнен, потрачено времени - 1 час
