### ISSUE TITLE
№ 45 Прописать сиды для всех статусов(OrderStatus)

### ISSUE THREAD

**Issue by primbayev** [CRM-system/crm#45]
## Конечный результат
Нужно прописать сиды для всех статусов, чтобы заполнить модель OrderStatus.

## Зачем это нужно
Чтобы админ сам не создавал записи в модели OrderStatus.

## Критерии приемки 
В консоли нужно написать команду выводящую все записи из модели OrderStatus

## Планируемое время работы
1 час

**Comment by Danny-Marco** [comment]
Написал сиды всех статусов.Затраченное время 40 мин
