### ISSUE TITLE
№ 46 Написать функционал добавления статусов(OrderStatus) и ролей в промежуточную таблицу(RoleOrderStatus)

### ISSUE THREAD

**Issue by primbayev** [CRM-system/crm#46]
## Конечный результат
Нужно написать action arrange_statuses, который будет принимать id роли и массив id-шек статусов. Используя данные параметры данный action должен создать записи в модели RoleOrderStatus.

## Зачем это нужно
Для реализации прав пользователей по статусам.

## Планируемое время работы
3 час

**Comment by Danny-Marco** [comment]
Реализовал функционал. Задачу помог решить аналитик команды (Алдияр). Потратил 12 часов.Решил не создавать отдельный контроллер ,а написать всё в контроллере update.
