### ISSUE TITLE
№ 47 Поменять вьюху roles#edit

### ISSUE THREAD

**Issue by primbayev** [CRM-system/crm#47]
## Конечный результат
В этой вьюхе будут меняться права пользователей по статусам.

## Зачем это нужно
Для проверки функционала в котором меняются права пользователей по статусам.

## Планируемое время работы
3 часа

**Comment by kairat-symanov** [comment]
Тикет исполнен, во вьюхе роль-эдит вывел названия всех статусов чекбоксами. На данной странице можно выбрать какие статусы можно предоставить сотруднику по клику на чекбокс. 
Потрачено времени  1,5 часа.
