### ISSUE TITLE
№ 49 Сделать двуязычие проекта

### ISSUE THREAD

**Issue by primbayev** [CRM-system/crm#49]
## Конечный результат
В yml-файле нужно сделать перевод всех статусов в модели Order. В модели OrderStatus нужно добавить column, который будет переводом поля title.Так же сделать перевод всех ошибок.

## Зачем это нужно
Чтобы пользователи crm-системы все понимали.

## Критерии приемки 
В списке заказов статусы указаны на русском языке. В странице обработки заказов статусы указаны на русском языке.Информация об ошибках должна выводиться на русском языке.

## Планируемое время работы
3 часа

**Comment by Danny-Marco** [comment]
Реализовал тикет. Потратил 2 часа.Использовалось парное программирование с аналитиком(Алдияром).
