### ISSUE TITLE
№ 52 Изменить дизайн вьюхи 'admin/functions/index'

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#52]
## Конечный результат
Вьюха 'functions/index' должна быть интуитивно понятной, не содержать информации не несущей смысловой нагрузки для пользователя.

## Зачем это нужно
На данный момент вьюха перегружена .Пользователь видит много не нужной информации.

## Критерии приемки 
1.в таблице вьюхи должны быть поля:
- Описание
  Вывод информации о функции.
- Доступ 
   Если 'true' пользователь видит иконку thumbs up зелёного цвета
   Если 'false' пользователь видит иконку thumbs down красного цвета
- Действия 
   Слова  'ограничить в правах' должны быть заменены иконкой 'minus circle' красного цвета
   Слова 'предоставить право' должны быть заменены иконкой 'check square' зелёного цвета
   Слово 'редактировать' должно быть заменено иконкой circular 'teal inverted pencil alternate icon'

2.из вьюхи '/admin/roles/edit' убрать кнопку 'Создать новую функцию'.

## Планируемое время работы
2 часа.

**Comment by kairat-symanov** [comment]
Тикет исполнен, потрачено 2 часа времени.
