### ISSUE TITLE
№ 53 Добавить вёрстку выпадающешго меню фильтров на страницу admin/orders/index

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#53]
## Конечный результат

На странице admin/orders/index должно появиться выпадающее меню ,которое можно свернуть и развернуть.Внутри меню должен быть реализован функционал поиска по фильтрам.

## Зачем это нужно
Если будет осуществляться большое количество заказов, пользователю будет затруднительно ориентироваться в заказах поэтому пользователь должен иметь возможность осуществлять поиск по фильтрам. Данное требование было согласовано на встрече с заказчиком.

## Критерии приемки 

На странице admin/orders/index должно появиться выпадающее меню ,которое можно свернуть и развернуть.На данном этапе только вёрстка.Внутри меню должны быть:
1. фильтр по дате:
    включив фильтр пользователь должен увидеть вывод заказов за:
    - вчера
    - сегодня
    - текущий месяц
    - текущий год
    - всё время
    - указанный период
2. тип доставки
3. название товара

## Планируемое время работы
3 часа

**Comment by aibek-abenov** [comment]
Потратил 4 часа
