### ISSUE TITLE
№ 54 Подключить гем pg_search

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#54]
## Конечный результат
В приложении должен быть установлен gem 'pg_search'

## Зачем это нужно
Это нужно для реализации поиска данных по всему приложению и вывода данных при помощи фильтров

## Критерии приемки 

  гем должен быть установлен.Всё должно корректно работать.

## Планируемое время работы
2 часа

**Comment by aibek-abenov** [comment]
Потратил 2 часа
