### ISSUE TITLE
№ 55 Реализация логики по выводу данных через фильтры

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#55]
## Конечный результат
  Написать логику(обмен данными в контроллере) функционала поиска по фильтрам.То есть пользователь должен иметь возможность выбрать вывод данных о конкретном заказе по:
1. фильтр по дате:
    включив фильтр пользователь должен увидеть вывод заказов за:
    - вчера
    - сегодня
    - текущий месяц
    - текущий год
    - всё время
    - указанный период
2. тип доставки.
3. название товара
4.данные заказчика
    - Ф.И.О
5.ID товара

## Зачем это нужно

Если будет осуществляться большое количество заказов, пользователю будет затруднительно ориентироваться в заказах поэтому пользователь должен иметь возможность осуществлять поиск по фильтрам. Данное требование было согласовано на встрече с заказчиком.

## Критерии приемки

Пользователь должен иметь возможность вывести информацию о заказе через фильтры ,которые он сам выберет.В таблице должна выводиться информация ,согласно фильтрам.То есть из вьюхи  admin/orders должны прийти данные из формы с параметрами фильтров поиска.Все данные должны приходить, обрабатываться и на странице admin/orders информация должна выводиться согласно фильтрам. 

## Планируемое время работы
6 часов

**Comment by kairat-symanov** [comment]
Реализовал 3 и 4 пункты данного тикета, потрачено много времени, **12 часов**

**Comment by kairat-symanov** [comment]
Реализован поиск по данным клиента и типу доставки, но работают по отдельности.

**Comment by kairat-symanov** [comment]
Тикет реализован, работают п. 2, 3, 4., потрачено много времени - 25 часов, реализовывал совместно с Данилом(парное программирование). Настала необходимость закрыть тикет и перенести реализацию п. 1 в следующий тикет.
