### ISSUE TITLE
№ 56 Реализовать логику вывода типа доставки для модели Order.

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#56]
## Конечный результат
Во вьюхе admin/orders/edit  должен быть селект, в котором будут выводиться все типы доставки.Выбрав один из типов доставки в таблицу orders должна быть записана информация которая была выбрана в селекте.  

## Зачем это нужно
Функционал реализовывается для того чтобы пользователь имел возможность выбрать тип доставки в фильтре вывода информации во вьюхе admin/orders. Данное решение было обсуждено с заказчиком на встрече

## Критерии приемки 
В модели Order должен быть список всех типов доставки(использовать 'enum' ).
  - курьер
  - почта
  - самовывоз

При обработке  заказа сотрудником должен быть выбран тип доставки из существующего списка и записан в базу данных.При выводе информации о заказе должен быть выведен тип доставки.А так же в фильтре должен выводиться селект всех типов доставки для фильтрации.  

## Планируемое время работы
2 часа

**Comment by primbayev** [comment]
Сделал тикет за 1 час
