### ISSUE TITLE
№ 60 Приёмочное тестирование по Геркин сценарию для входа на страницу авторизации

### ISSUE THREAD

**Issue by kairat-symanov** [CRM-system/crm#60]
## Конечный результат
Написать приёмочный тест для входа на страницу авторизации, который должен быть успешно пройден(тест должен быть зелёный)
## Зачем это нужно
Для корректной работы приложения необходимо прогонять тесты, чтобы приложение работало корректно. В дальнейшем необходимо прогонять тесты (при изменении кода), чтобы обнаружить поломки приложения, при завале приложения необходимо найти ошибку и исправить.
## Критерии приемки
Пользователь должен зайти на сайт  и увидеть кнопку "Войти". Нажав на кнопку "Войти" пользователь должен провалиться на страницу авторизации.
## Планируемое время работы
3 часа

**Comment by primbayev** [comment]
Сделал за 1 час
