### ISSUE TITLE
№ 61 Приёмочное тестирование по Геркин сценарию для авторизации пользователя

### ISSUE THREAD

**Issue by kairat-symanov** [CRM-system/crm#61]
## Конечный результат
Написать приёмочный тест для авторизации, который должен быть успешно пройден(тест должен быть зелёный)
## Зачем это нужно
Для корректной работы приложения необходимо прогонять тесты, чтобы приложение работало корректно. В дальнейшем необходимо прогонять тесты (при изменении кода), чтобы обнаружить поломки приложения, при завале приложения необходимо найти ошибку и исправить.
## Критерии приемки
Пользователь на странице авторизации видит форму с полями ввода э**л. почты, пароля и кнопку ввода**. Заполнив все поля пользователь должен провалиться на админскую страницу и увидеть навбар с ссылками "Товары", "Должности", "Сотрудники", "Заказы".
## Планируемое время работы
3 часа

**Comment by primbayev** [comment]
Сделал за 2 часа
