### ISSUE TITLE
№62 Приёмочное тестирование по Геркин сценарию для Должности.

### ISSUE THREAD

**Issue by kairat-symanov** [CRM-system/crm#62]
## Конечный результат
Написать приёмочный тест для создания,удаления и редактирования новой должности на странице admin/roles, (тест должен быть зелёный).
## Зачем это нужно
Для корректной работы приложения необходимо прогонять тесты, чтобы приложение работало корректно. В дальнейшем необходимо прогонять тесты (при изменении кода), чтобы обнаружить поломки приложения, при завале приложения необходимо найти ошибку и исправить.
## Критерии приемки
Пользователь должен зайти на сайт  и увидеть кнопку "Создать новую должность". Нажав на нее пользователь создает должность ,после создания увидеть в списке должностей созданную должность.Затем кликнув на созданную должность увидеть кнопку "Редактировать".Кликнув на нее можно будет увидеть форму редактирования.Отредактировать должность(изменить название должности),после  увидеть в списке должностей отредактированную должность .В этом же списке напротив отредактированной должности увидеть кнопку удаления,нажав на нее удалить эту должность.
## Планируемое время работы
3 часа

**Comment by primbayev** [comment]
Сделал за 6 часов.
