### ISSUE TITLE
№63 Приёмочное тестирование по Геркин сценарию для Сотрудника.

### ISSUE THREAD

**Issue by aibek-abenov** [CRM-system/crm#63]
## Конечный результат
Написать приёмочный тест для создания,удаления и редактирования новой должности на странице admin/workers, (тест должен быть зелёный).
## Зачем это нужно
Для корректной работы приложения необходимо прогонять тесты, чтобы приложение работало корректно. В дальнейшем необходимо прогонять тесты (при изменении кода), чтобы обнаружить поломки приложения, при завале приложения необходимо найти ошибку и исправить.
## Критерии приемки
Пользователь должен зайти на admin/workers  и увидеть кнопку "Создать нового сотрудника". Нажав на нее пользователь создает сотрудника ,после создания увидеть в списке сотрудников созданного сотрудника.В списке напротив созданного сотрудника увидеть кнопку редактирования,нажав на нее увидеть форму редактирования,затем поменяв имя сотрудника и сохраняет сотрудника.После редактирования увидеть в списке сотрудников отредактированного сотрудника, возле кнопки редактирования должен увидеть кнопку удаления.Нажав на нее удалить сотрудника. 
## Планируемое время работы
4 часа

**Comment by Danny-Marco** [comment]
Написал тест на создание сотрудника.Потратил 4 часа.Ещё нужно написать тесты на редактирование и удаление сотрудника.

**Comment by Danny-Marco** [comment]
Переписал код для тестирования с тестовой базой данных и сидами.
