### ISSUE TITLE
№ 66 Изучить базовые функции Postman-a

### ISSUE THREAD

**Issue by kairat-symanov** [CRM-system/crm#66]
## Конечный результат:
Иметь базовые знания о Postman
## Зачем это нужно:
Через него мы сможем наглядно посмотреть, какой ответ будет приходить, когда кто-то будет вызывать методы в нашем API
## Критерии приёмки:
Уметь пользоваться Postman-ом
## Планируемое время:
4 часа

**Comment by primbayev** [comment]
На изучение данной платформы ушло больше времени. Ее изучение оказалось сложнее чем мы думали
