### ISSUE TITLE
№ 68 Изучить гем factory_bot_rails.

### ISSUE THREAD

**Issue by aibek-abenov** [CRM-system/crm#68]
## Конечный результат:
Установить гем и пользоваться в данном приложении
## Зачем это нужно:
Уметь тестировать приложение без вреда для базы данных.
## Критерии приёмки:
Объяснить команде как использовать **gem factory_bot _rails**
## Планируемое время:
4 часа

**Comment by Danny-Marco** [comment]
Изучил factory_bot_rails.Подключил gem "factory_bot_rails".Потратил 7 часов.

**Comment by aibek-abenov** [comment]
Изучил factory_bot_rails по видео.Имею кое какое представление.
