### ISSUE TITLE
№ 69 Написать приемочное тестирование для Статусов.

### ISSUE THREAD

**Issue by aibek-abenov** [CRM-system/crm#69]
## Конечный результат
Написать приёмочный тест для проверки ссылок Статусов странице admin/orders, (тест должен быть зелёный).
## Зачем это нужно
Для корректной работы приложения необходимо прогонять тесты, чтобы приложение работало корректно. В дальнейшем необходимо прогонять тесты (при изменении кода), чтобы обнаружить поломки приложения, при завале приложения необходимо найти ошибку и исправить.
## Критерии приемки
Пользователь должен зайти на admin/orders  и увидеть ссылки - статусы.По клику на которых список заказов будет возвращать заказы с требуемыми  статусами. 
## Планируемое время работы
4 часа

**Comment by kairat-symanov** [comment]
Тикет №69 **тестирование ссылок** исполнен, все ссылки проходят тестирование.
Потрачено 16 часов.
Также добавил **id-шки** к ссылкам, по рекомендации саппорта.
