### ISSUE TITLE
№7 - Создать сущность Function

### ISSUE THREAD

**Issue by kairat-symanov** [CRM-system/crm#7]
Конечный результат:
Создать сущность Function 
План решения:
- создать модель Function с полями:name:string,acceess:boolean(default:false);functionable_id:integer,functionable_type:string 
-связь с таблицей role(belongs_to)
- создать контроллер Functions,весь CRUD, 
Мотивация:
Для добавления функций для каждой должности.

**Comment by primbayev** [comment]
Начал работу над созданием данной сущности. Решил сделать по другому, потому что вышла проблема.

**Comment by Danny-Marco** [comment]
Обсуждали возникшую проблему с командой.На обсуждение был потрачен час.На поиск решения самостоятельно был потрачен час.

**Comment by kairat-symanov** [comment]
Возникла проблема с реализацией этого тикета, полиморфная связь не дала результатов. Обсуждали возникшую проблему с командой и решили сделать обычные связи таблиц. На обсуждение был потрачен час.

**Comment by primbayev** [comment]
Создал сущность Function, сделал все основные actions. На работу было потрачено 8 часов
