### ISSUE TITLE
№ 71 Реализовать поставку приложения на сервер.

### ISSUE THREAD

**Issue by aibek-abenov** [CRM-system/crm#71]
## Конечный результат:
Реализовать поставку приложения на сервер.
## Зачем это нужно:
Для того чтобы Заказчик пользовался приложением.
## Критерии приёмки:
Пользоваться приложением удаленно.
## Планируемое время:
6 часов

**Comment by Danny-Marco** [comment]
Сделал поставку на сервер.Потратил неделю.Пытался реализовать поставку через CI машину.
