### ISSUE TITLE
№ 72 Написать не большое приложение для Landing 

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#72]
## Конечный результат
Написать приложение которое будет отображать какой-нибудь товар 
## Зачем это нужно
Для проверки взаимодействия приложения crm по API.
## Критерии приемки
Должно быть полностью рабочее приложение выложенное в открытый репозитроий на GitHub
В приложении должна быть подключена БД POstgresQL

**Comment by aibek-abenov** [comment]
Потратил 2,5 часа
