### ISSUE TITLE
№ 73 Сделать поставку приложения Landing на удалённый сервер

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#73]
## Конечный результат
Сделать поставку приложения на удалённый сервер. 
## Зачем это нужно
Для проверки взаимодействия приложения crm и Landing по API.
## Критерии приемки
-приложение должно быть выложено на удалённый сервер и доступно через браузер

**Comment by kairat-symanov** [comment]
Сделал поставку лендинга, **первые 16 часов** пытался сделать деплой вручную. Не получилось. 
После занятия по деплою через капистрано, получилось сделать деплой, было много конфликтов, после их решения деплой сделал. 188.166.101.186 - по этому ip можно зайти через браузер.
Потратил **23 часа**
