### ISSUE TITLE
№ 74 Исправить вывод комментариев

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#74]
## Конечный результат
Исправить вывод комментариев во вьюхе orders. 
## Зачем это нужно
Для интуитивно понятного и приятного отображения комментариев.
## Критерии приемки
-в форме обработки заказов должно отображаться поле для ввода комментариев
-во вьюхе отображения комментариев должна выводиться таблица с:
 информацией о том кто оставил комментарий (имя, должность)
 сам комментарий
в верхней части вьюхи (вне таблицы) должно выводится название товара 

## Планируемое время работы
3 часа

**Comment by aibek-abenov** [comment]
Потратил 5 часов
