### ISSUE TITLE
№ 75 написать API для приложений Landing page и CRM

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#75]
## Конечный результат
Написать API для обоих приложений и сделать запросы между приложениями. 
## Зачем это нужно
Для того чтобы реализовать функционал заказа товара.
## Критерии приемки
-Оба приложения должны делать запросы друг-другу и возвращать данные
## Планируемое время работы
4 часа

**Comment by primbayev** [comment]
Решил за 2 недели
