### ISSUE TITLE
№ 77 Реализовать вывод последнего комментария

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#77]
## Конечный результат
Реализовать вывод последнего комментария в таблице заказов. 
## Зачем это нужно
Данное требование было обговорено с заказчиком.
## Критерии приемки
В таблице заказов, в поле комментарий должен отображаться последний комментарий если он есть.А если нет комментариев - то должно отображаться пустое поле.
## Планируемое время работы
3 часа

**Comment by aibek-abenov** [comment]
Потратил 2 часа
