### ISSUE TITLE
№ 78 Написать тесты для вьюхи orders

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#78]
## Конечный результат
Написать тесты для вьюхи Orders. 
## Зачем это нужно
Для проверки стабильной работы приложения.
## Критерии приемки
-весь функционал вьюхи Orders полностью должен быть покрыт тестами
-протестировать обработку заказа
-протестировать удаление заказа 
## Планируемое время работы
6 часов

**Comment by aibek-abenov** [comment]
Потратил 8 часов
