### ISSUE TITLE
№ 79 сверстать Лендинг в приложении Lending

### ISSUE THREAD

**Issue by Danny-Marco** [CRM-system/crm#79]
## Конечный результа.
Сверстать лендинг в приложении Lendind  дл отображения на удалённом сервере
## Зачем это нужно
Для проверки работы приложения через API
## Критерии приемки
-на отдельном удалённом сервере должен быть виден лендинг 
## Планируемое время работы
3 часа

**Comment by aibek-abenov** [comment]
Потратил 6 часов
