### ISSUE TITLE
№8 - Создать сущность Role

### ISSUE THREAD

**Issue by kairat-symanov** [CRM-system/crm#8]
Конечный результат:
Создать сущность Role, которая будет связана с таблицами Function и Worker(has_many)
План решения:
- создать модель Role с полем name:string
- связать все таблицы миграциями;
-реализовать весь CRUD
-создать вьюхи new, edit, show, index.
  во вьюхе show должны быть кнопки:удалить и редактировать.И соответственно переход в форму 
  edit по кнопке редактировать.

-добавить в навбар ссылку должности
Мотивация:
Для предоставления админом сотрудникам необходимых функций.

**Comment by Danny-Marco** [comment]
В связи с изменением варианта решения задачи, задача отложена на поздний срок.

**Comment by kairat-symanov** [comment]
В конце работы прошу всех оставлять свои комментарии в тикетах по проделанной работе и потраченного времени.
Данный тикет отработан?

**Comment by aibek-abenov** [comment]
Реализовал все требования тикета.
Потребовалось 6 часов.
