### ISSUE TITLE
№ 80 Создать модель landing

### ISSUE THREAD

**Issue by primbayev** [CRM-system/crm#80]
## Конечный результат.
В приложении должна присутствовать модель landing, и все CRUD операции
## Зачем это нужно
Для того чтобы стороннее приложение могло получать список товаров одной категории
## Критерии приемки
Модель landing и product, имеют связь один ко многим. В приложении можно выполнять все CRUD операции
## Планируемое время работы
3 часа

**Comment by kairat-symanov** [comment]
Создал сущность Landing, потратил **10 часов**
