### ISSUE TITLE
№ 84 Пофиксить вывод данных по списку

### ISSUE THREAD

**Issue by kairat-symanov** [CRM-system/crm#84]
## Критерии приёмки:
В моделях "Заказы", "Должности" список должен быть в порядке убывания
## Зачем это нужно:
Списки должны быть в уьывающем порядке, а не в разнобой
## Критерии приёмки:
В браузере пользователь должен видеть списки в убывающем порядке
## Планируемое время:
1 час

**Comment by Danny-Marco** [comment]
Сделал вывод данных в таблицах по порядку.Потратил 30 минут
