### ISSUE TITLE
№ 86 Редактирование товара в заказе

### ISSUE THREAD

**Issue by kairat-symanov** [CRM-system/crm#86]
## Конечный результат:
Оператор может поменять товар (по цвету, размеру и др. параметрам) при обработке заказа
## Зачем это нужно:
Дать возможность клиенту выбирать товар по параметрам (по цвету, размеру и др. параметрам)
## Критерии приёмки:
При обработке заказа оператор должен иметь возможность поменять товар (по цвету, размеру и др. параметрам) по требованию клиента, выбрав из выпадающего окна (селект) в форме обработки заказа
## Планируемое время:
4 часа

**Comment by primbayev** [comment]
Сделал за 20 минут
