### ISSUE TITLE
№9 - Полиморфные связи

### ISSUE THREAD

**Issue by kairat-symanov** [CRM-system/crm#9]
Конечный результат:
Изучить полиморфные связи, для понимания как связать модели проекта.
План решения:
Изучить полиморфные связи:
- в интернете поискать доступную информацию, желательно официальную документацию;
- прочитать материал и в составе команды обсудить, пока все не поймут принцип работы;
- при необходимости делать комментарии в данном тикете;
Мотивация:
Необходимая информация для каждого из нас, в дальнейшем пригодится.  
Обсуждение 12.01.2019.

**Comment by kairat-symanov** [comment]
Изучил пример полиморфной связи на сайте https://habr.com/post/79431/

**Comment by aibek-abenov** [comment]
Изучил пример полиморфной связи на сайте https://habr.com/post/79431/

**Comment by primbayev** [comment]
Изучил полиморфные связи

**Comment by Danny-Marco** [comment]
Изучил связи.Обсудил с коммандой

**Comment by aibek-abenov** [comment]
Изучил связи.Обсудил с коммандой
